version: "3"
services:
  app:
    container_name: pythonapp
    build:
      context: ./app
      dockerfile: Dockerfile 
    expose:
      - "8000"
    environment:
      - FLASK_ENV=development
    command: python3 server.py
    networks:
      - exercise

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/files/localhost.crt:/etc/ssl/localhost.crt
      - ./nginx/files/localhost.key:/etc/ssl/localhost.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - exercise

networks:
  exercise:
